apiVersion: v1
kind: ReplicationController
metadata: 
 name: myrcpod
spec:
 replicas: 4
 template:
  metadata:
   labels:
    app: test
  spec:
   containers:
    - image: nginx
      name: mycont
      ports:
       - containerPort: 80
      readinessProbe:
         httpGet:
          path: /index.html
          port: 80
